select initcap('hello') from dual;
select lower('hello') from dual;
select upper('hello') from dual;
select length('hello') from dual;
select ltrim('    hello') from dual;
select rtrim('hello    ') from dual;
select translate('jack','j','b') from dual;
select replace('jack','j','bl') from dual;
select instr('oracle','a') from dual;
select substr('oracle10g',7,3) from dual;
select concat('oracle','10g') from dual;
select months_between(to_date('2018-02-16','yyyy-mm-dd'),sysdate) from dual;
select add_months(sysdate,5) from dual;
select next_day(sysdate+12,5) from dual;
select last_day(sysdate+57) from dual;
select to_char(sysdate,'yyyy"Äê"mm"ÔÂ"dd"ÈÕ"') from dual;
select lower('hello') from dual;
select lower('hello') from dual;
select lower('hello') from dual;
select lower('hello') from dual;
select lower('hello') from dual;
